services:
  mysql:
    image: mysql@sha256:eeabfa5cd6a2091bf35eb9eae6ae48aab8231fd760f5a61cd0129df454333b1d
    container_name: "go-crypto-challenge-db"
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - .docker/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 20s
      start_interval: 5s
  api:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    env_file: .env
    environment:
      DATABASE_HOST: mysql
    ports:
      - "3000:3000"
    cap_drop:
      - ALL
    cap_add:
      - SETUID
    read_only: true
    depends_on:
      mysql:
        condition: service_healthy
